//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public short CategoryID { get; set; }
        public byte PriorityID { get; set; }
        public byte StatusID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Subject { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<long> AssigneeID { get; set; }
        public long ProductID { get; set; }
        public string Body { get; set; }
        public long OrganizationID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
